real pi, radio, perimetro, area, volumen
inicio
escriba "introduzca el radio del circulo"
lea radio
pi <- 3.1416
perimetro <- (2*pi*radio)
area <- (pi*radio*radio)
volumen <- (4*pi*radio*radio*radio/3)
escriba "perimetro: 2 * ",pi, " * ", radio, perimetro
llamar nueva_linea
escriba "area:",pi, " * ",radio, " elevado al cuadrado ", area 
llamar nueva_linea
escriba " volumen: 4 * ", pi, " * ",radio," elevado al cubo / 3 ", volumen
fin 
 